/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'spiritualNeeds' : IDL.Text,
  'lifeSituation' : IDL.Text,
  'name' : IDL.Text,
});
export const State = IDL.Variant({
  'pendingModeration' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const Testimony = IDL.Record({
  'moderatorNote' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'disclaimers' : IDL.Vec(IDL.Text),
  'authorId' : IDL.Principal,
  'labels' : IDL.Vec(IDL.Text),
  'state' : State,
  'scriptureReferences' : IDL.Vec(IDL.Text),
});
export const BibleTranslation = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'abbreviation' : IDL.Text,
});
export const BibleBook = IDL.Record({
  'id' : IDL.Nat,
  'translationId' : IDL.Nat,
  'name' : IDL.Text,
  'abbreviation' : IDL.Text,
});
export const BibleChapter = IDL.Record({
  'id' : IDL.Nat,
  'bookId' : IDL.Nat,
  'number' : IDL.Text,
});
export const ScriptureEntry = IDL.Record({
  'references' : IDL.Vec(IDL.Text),
  'contentKind' : IDL.Text,
  'labels' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'motivation' : IDL.Text,
});
export const DiscernmentReflection = IDL.Record({
  'references' : IDL.Vec(IDL.Text),
  'content' : IDL.Text,
  'contentKind' : IDL.Text,
  'labels' : IDL.Vec(IDL.Text),
});
export const FeedItem = IDL.Record({
  'id' : IDL.Nat,
  'references' : IDL.Vec(IDL.Text),
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'originalItemId' : IDL.Opt(IDL.Nat),
  'repostCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'itemType' : IDL.Variant({
    'userPost' : IDL.Null,
    'scriptureEntry' : IDL.Null,
    'aiAgentPost' : IDL.Null,
    'reflection' : IDL.Null,
    'testimony' : IDL.Null,
  }),
});
export const LastBibleLocation = IDL.Record({
  'translationId' : IDL.Nat,
  'bookId' : IDL.Nat,
  'chapterId' : IDL.Nat,
  'verseId' : IDL.Opt(IDL.Nat),
  'scrollAnchor' : IDL.Opt(IDL.Nat),
});
export const AgentResponse = IDL.Record({
  'agentReply' : IDL.Text,
  'references' : IDL.Vec(IDL.Text),
  'originalMessage' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BibleVerse = IDL.Record({
  'id' : IDL.Nat,
  'translationId' : IDL.Nat,
  'bookName' : IDL.Text,
  'verseNumber' : IDL.Text,
  'chapterNumber' : IDL.Text,
  'text' : IDL.Text,
  'bookId' : IDL.Nat,
  'chapterId' : IDL.Nat,
  'translationName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'approveTestimony' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgentPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'createAgentResponse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createDiscernmentReflection' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'createScriptureEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getApprovedTestimonies' : IDL.Func([], [IDL.Vec(Testimony)], ['query']),
  'getAvailableBibleTranslations' : IDL.Func(
      [],
      [IDL.Vec(BibleTranslation)],
      ['query'],
    ),
  'getBooksForTranslation' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BibleBook)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChaptersForBook' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BibleChapter)],
      ['query'],
    ),
  'getDailyFeed' : IDL.Func(
      [],
      [
        IDL.Vec(ScriptureEntry),
        IDL.Vec(DiscernmentReflection),
        IDL.Vec(Testimony),
      ],
      ['query'],
    ),
  'getDiscernmentReflections' : IDL.Func(
      [],
      [IDL.Vec(DiscernmentReflection)],
      ['query'],
    ),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(FeedItem)], ['query']),
  'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getLastBibleLocation' : IDL.Func(
      [],
      [IDL.Opt(LastBibleLocation)],
      ['query'],
    ),
  'getLatestAgentPost' : IDL.Func([], [IDL.Opt(FeedItem)], ['query']),
  'getResponsesToUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AgentResponse)],
      ['query'],
    ),
  'getScriptureByTranslation' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(ScriptureEntry))],
      ['query'],
    ),
  'getScriptureEntries' : IDL.Func([], [IDL.Vec(ScriptureEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVersesForChapter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(BibleVerse)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectTestimony' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'removeReaction' : IDL.Func([IDL.Nat], [], []),
  'repostItem' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVerse' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Opt(BibleVerse)],
      ['query'],
    ),
  'setLastBibleLocation' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'setLastBibleLocationWithScroll' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'submitTestimony' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'spiritualNeeds' : IDL.Text,
    'lifeSituation' : IDL.Text,
    'name' : IDL.Text,
  });
  const State = IDL.Variant({
    'pendingModeration' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const Testimony = IDL.Record({
    'moderatorNote' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'disclaimers' : IDL.Vec(IDL.Text),
    'authorId' : IDL.Principal,
    'labels' : IDL.Vec(IDL.Text),
    'state' : State,
    'scriptureReferences' : IDL.Vec(IDL.Text),
  });
  const BibleTranslation = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'abbreviation' : IDL.Text,
  });
  const BibleBook = IDL.Record({
    'id' : IDL.Nat,
    'translationId' : IDL.Nat,
    'name' : IDL.Text,
    'abbreviation' : IDL.Text,
  });
  const BibleChapter = IDL.Record({
    'id' : IDL.Nat,
    'bookId' : IDL.Nat,
    'number' : IDL.Text,
  });
  const ScriptureEntry = IDL.Record({
    'references' : IDL.Vec(IDL.Text),
    'contentKind' : IDL.Text,
    'labels' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'motivation' : IDL.Text,
  });
  const DiscernmentReflection = IDL.Record({
    'references' : IDL.Vec(IDL.Text),
    'content' : IDL.Text,
    'contentKind' : IDL.Text,
    'labels' : IDL.Vec(IDL.Text),
  });
  const FeedItem = IDL.Record({
    'id' : IDL.Nat,
    'references' : IDL.Vec(IDL.Text),
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'originalItemId' : IDL.Opt(IDL.Nat),
    'repostCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'itemType' : IDL.Variant({
      'userPost' : IDL.Null,
      'scriptureEntry' : IDL.Null,
      'aiAgentPost' : IDL.Null,
      'reflection' : IDL.Null,
      'testimony' : IDL.Null,
    }),
  });
  const LastBibleLocation = IDL.Record({
    'translationId' : IDL.Nat,
    'bookId' : IDL.Nat,
    'chapterId' : IDL.Nat,
    'verseId' : IDL.Opt(IDL.Nat),
    'scrollAnchor' : IDL.Opt(IDL.Nat),
  });
  const AgentResponse = IDL.Record({
    'agentReply' : IDL.Text,
    'references' : IDL.Vec(IDL.Text),
    'originalMessage' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BibleVerse = IDL.Record({
    'id' : IDL.Nat,
    'translationId' : IDL.Nat,
    'bookName' : IDL.Text,
    'verseNumber' : IDL.Text,
    'chapterNumber' : IDL.Text,
    'text' : IDL.Text,
    'bookId' : IDL.Nat,
    'chapterId' : IDL.Nat,
    'translationName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'approveTestimony' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgentPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'createAgentResponse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createDiscernmentReflection' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'createScriptureEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getApprovedTestimonies' : IDL.Func([], [IDL.Vec(Testimony)], ['query']),
    'getAvailableBibleTranslations' : IDL.Func(
        [],
        [IDL.Vec(BibleTranslation)],
        ['query'],
      ),
    'getBooksForTranslation' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BibleBook)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChaptersForBook' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BibleChapter)],
        ['query'],
      ),
    'getDailyFeed' : IDL.Func(
        [],
        [
          IDL.Vec(ScriptureEntry),
          IDL.Vec(DiscernmentReflection),
          IDL.Vec(Testimony),
        ],
        ['query'],
      ),
    'getDiscernmentReflections' : IDL.Func(
        [],
        [IDL.Vec(DiscernmentReflection)],
        ['query'],
      ),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(FeedItem)], ['query']),
    'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getLastBibleLocation' : IDL.Func(
        [],
        [IDL.Opt(LastBibleLocation)],
        ['query'],
      ),
    'getLatestAgentPost' : IDL.Func([], [IDL.Opt(FeedItem)], ['query']),
    'getResponsesToUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AgentResponse)],
        ['query'],
      ),
    'getScriptureByTranslation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(ScriptureEntry))],
        ['query'],
      ),
    'getScriptureEntries' : IDL.Func([], [IDL.Vec(ScriptureEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVersesForChapter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(BibleVerse)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectTestimony' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'removeReaction' : IDL.Func([IDL.Nat], [], []),
    'repostItem' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVerse' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Opt(BibleVerse)],
        ['query'],
      ),
    'setLastBibleLocation' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'setLastBibleLocationWithScroll' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'submitTestimony' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };