/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentResponse {
  'agentReply' : string,
  'references' : Array<string>,
  'originalMessage' : string,
  'timestamp' : bigint,
}
export interface BibleBook {
  'id' : bigint,
  'translationId' : bigint,
  'name' : string,
  'abbreviation' : string,
}
export interface BibleChapter {
  'id' : bigint,
  'bookId' : bigint,
  'number' : string,
}
export interface BibleTranslation {
  'id' : bigint,
  'name' : string,
  'abbreviation' : string,
}
export interface BibleVerse {
  'id' : bigint,
  'translationId' : bigint,
  'bookName' : string,
  'verseNumber' : string,
  'chapterNumber' : string,
  'text' : string,
  'bookId' : bigint,
  'chapterId' : bigint,
  'translationName' : string,
}
export interface DiscernmentReflection {
  'references' : Array<string>,
  'content' : string,
  'contentKind' : string,
  'labels' : Array<string>,
}
export interface FeedItem {
  'id' : bigint,
  'references' : Array<string>,
  'content' : string,
  'authorId' : Principal,
  'originalItemId' : [] | [bigint],
  'repostCount' : bigint,
  'timestamp' : bigint,
  'itemType' : { 'userPost' : null } |
    { 'scriptureEntry' : null } |
    { 'aiAgentPost' : null } |
    { 'reflection' : null } |
    { 'testimony' : null },
}
export interface LastBibleLocation {
  'translationId' : bigint,
  'bookId' : bigint,
  'chapterId' : bigint,
  'verseId' : [] | [bigint],
  'scrollAnchor' : [] | [bigint],
}
export interface ScriptureEntry {
  'references' : Array<string>,
  'contentKind' : string,
  'labels' : Array<string>,
  'text' : string,
  'motivation' : string,
}
export type State = { 'pendingModeration' : null } |
  { 'approved' : null } |
  { 'rejected' : string };
export interface Testimony {
  'moderatorNote' : [] | [string],
  'content' : string,
  'disclaimers' : Array<string>,
  'authorId' : Principal,
  'labels' : Array<string>,
  'state' : State,
  'scriptureReferences' : Array<string>,
}
export interface UserProfile {
  'spiritualNeeds' : string,
  'lifeSituation' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, Array<string>, boolean], bigint>,
  'addReaction' : ActorMethod<[bigint, string], undefined>,
  'approveTestimony' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgentPost' : ActorMethod<[string, Array<string>], bigint>,
  'createAgentResponse' : ActorMethod<
    [string, string, Array<string>],
    undefined
  >,
  'createDiscernmentReflection' : ActorMethod<
    [string, Array<string>, Array<string>, string],
    undefined
  >,
  'createOrUpdateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'createPost' : ActorMethod<[string, Array<string>], bigint>,
  'createScriptureEntry' : ActorMethod<
    [string, string, Array<string>, Array<string>, string],
    undefined
  >,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getApprovedTestimonies' : ActorMethod<[], Array<Testimony>>,
  'getAvailableBibleTranslations' : ActorMethod<[], Array<BibleTranslation>>,
  'getBooksForTranslation' : ActorMethod<[bigint], Array<BibleBook>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChaptersForBook' : ActorMethod<[bigint], Array<BibleChapter>>,
  'getDailyFeed' : ActorMethod<
    [],
    [Array<ScriptureEntry>, Array<DiscernmentReflection>, Array<Testimony>]
  >,
  'getDiscernmentReflections' : ActorMethod<[], Array<DiscernmentReflection>>,
  'getFeed' : ActorMethod<[bigint, bigint], Array<FeedItem>>,
  'getFollowersCount' : ActorMethod<[Principal], bigint>,
  'getFollowingCount' : ActorMethod<[Principal], bigint>,
  'getLastBibleLocation' : ActorMethod<[], [] | [LastBibleLocation]>,
  'getLatestAgentPost' : ActorMethod<[], [] | [FeedItem]>,
  'getResponsesToUser' : ActorMethod<[Principal], Array<AgentResponse>>,
  'getScriptureByTranslation' : ActorMethod<
    [string],
    [] | [Array<ScriptureEntry>]
  >,
  'getScriptureEntries' : ActorMethod<[], Array<ScriptureEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVersesForChapter' : ActorMethod<
    [bigint, bigint, bigint],
    Array<BibleVerse>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectTestimony' : ActorMethod<[Principal, string], undefined>,
  'removeReaction' : ActorMethod<[bigint], undefined>,
  'repostItem' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVerse' : ActorMethod<
    [bigint, bigint, bigint, string],
    [] | [BibleVerse]
  >,
  'setLastBibleLocation' : ActorMethod<
    [bigint, bigint, bigint, [] | [bigint]],
    undefined
  >,
  'setLastBibleLocationWithScroll' : ActorMethod<
    [bigint, bigint, bigint, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'submitTestimony' : ActorMethod<
    [string, Array<string>, Array<string>, Array<string>],
    undefined
  >,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];