/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BibleVerse {
    id: bigint;
    translationId: bigint;
    bookName: string;
    verseNumber: string;
    chapterNumber: string;
    text: string;
    bookId: bigint;
    chapterId: bigint;
    translationName: string;
}
export interface AgentResponse {
    agentReply: string;
    references: Array<string>;
    originalMessage: string;
    timestamp: bigint;
}
export interface ScriptureEntry {
    references: Array<string>;
    contentKind: string;
    labels: Array<string>;
    text: string;
    motivation: string;
}
export interface BibleBook {
    id: bigint;
    translationId: bigint;
    name: string;
    abbreviation: string;
}
export interface BibleChapter {
    id: bigint;
    bookId: bigint;
    number: string;
}
export interface BibleTranslation {
    id: bigint;
    name: string;
    abbreviation: string;
}
export interface FeedItem {
    id: bigint;
    references: Array<string>;
    content: string;
    authorId: Principal;
    originalItemId?: bigint;
    repostCount: bigint;
    timestamp: bigint;
    itemType: Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony;
}
export interface LastBibleLocation {
    translationId: bigint;
    bookId: bigint;
    chapterId: bigint;
    verseId?: bigint;
    scrollAnchor?: bigint;
}
export interface DiscernmentReflection {
    references: Array<string>;
    content: string;
    contentKind: string;
    labels: Array<string>;
}
export type State = {
    __kind__: "pendingModeration";
    pendingModeration: null;
} | {
    __kind__: "approved";
    approved: null;
} | {
    __kind__: "rejected";
    rejected: string;
};
export interface UserProfile {
    spiritualNeeds: string;
    lifeSituation: string;
    name: string;
}
export interface Testimony {
    moderatorNote?: string;
    content: string;
    disclaimers: Array<string>;
    authorId: Principal;
    labels: Array<string>;
    state: State;
    scriptureReferences: Array<string>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony {
    userPost = "userPost",
    scriptureEntry = "scriptureEntry",
    aiAgentPost = "aiAgentPost",
    reflection = "reflection",
    testimony = "testimony"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(itemId: bigint, content: string, references: Array<string>, isAgentReply: boolean): Promise<bigint>;
    addReaction(itemId: bigint, emoji: string): Promise<void>;
    approveTestimony(testimonyId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAgentPost(content: string, references: Array<string>): Promise<bigint>;
    createAgentResponse(originalMessage: string, agentReply: string, references: Array<string>): Promise<void>;
    createDiscernmentReflection(content: string, labels: Array<string>, references: Array<string>, contentKind: string): Promise<void>;
    createOrUpdateUserProfile(profile: UserProfile): Promise<void>;
    createPost(content: string, references: Array<string>): Promise<bigint>;
    createScriptureEntry(text: string, motivation: string, labels: Array<string>, references: Array<string>, contentKind: string): Promise<void>;
    followUser(userToFollow: Principal): Promise<void>;
    getApprovedTestimonies(): Promise<Array<Testimony>>;
    getAvailableBibleTranslations(): Promise<Array<BibleTranslation>>;
    getBooksForTranslation(translationId: bigint): Promise<Array<BibleBook>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChaptersForBook(bookId: bigint): Promise<Array<BibleChapter>>;
    getDailyFeed(): Promise<[Array<ScriptureEntry>, Array<DiscernmentReflection>, Array<Testimony>]>;
    getDiscernmentReflections(): Promise<Array<DiscernmentReflection>>;
    getFeed(limit: bigint, offset: bigint): Promise<Array<FeedItem>>;
    getFollowersCount(user: Principal): Promise<bigint>;
    getFollowingCount(user: Principal): Promise<bigint>;
    getLastBibleLocation(): Promise<LastBibleLocation | null>;
    getLatestAgentPost(): Promise<FeedItem | null>;
    getResponsesToUser(user: Principal): Promise<Array<AgentResponse>>;
    getScriptureByTranslation(translation: string): Promise<Array<ScriptureEntry> | null>;
    getScriptureEntries(): Promise<Array<ScriptureEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVersesForChapter(translationId: bigint, bookId: bigint, chapterId: bigint): Promise<Array<BibleVerse>>;
    isCallerAdmin(): Promise<boolean>;
    rejectTestimony(testimonyId: Principal, moderatorNote: string): Promise<void>;
    removeReaction(itemId: bigint): Promise<void>;
    repostItem(itemId: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchVerse(translationId: bigint, bookId: bigint, chapterId: bigint, verseNumber: string): Promise<BibleVerse | null>;
    setLastBibleLocation(translationId: bigint, bookId: bigint, chapterId: bigint, verseId: bigint | null): Promise<void>;
    setLastBibleLocationWithScroll(translationId: bigint, bookId: bigint, chapterId: bigint, verseId: bigint | null, scrollAnchor: bigint | null): Promise<void>;
    submitTestimony(content: string, labels: Array<string>, disclaimers: Array<string>, scriptureReferences: Array<string>): Promise<void>;
    unfollowUser(userToUnfollow: Principal): Promise<void>;
}
import type { BibleVerse as _BibleVerse, FeedItem as _FeedItem, LastBibleLocation as _LastBibleLocation, ScriptureEntry as _ScriptureEntry, State as _State, Testimony as _Testimony, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string, arg2: Array<string>, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addReaction(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return result;
        }
    }
    async approveTestimony(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTestimony(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTestimony(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAgentPost(arg0: string, arg1: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgentPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgentPost(arg0, arg1);
            return result;
        }
    }
    async createAgentResponse(arg0: string, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgentResponse(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgentResponse(arg0, arg1, arg2);
            return result;
        }
    }
    async createDiscernmentReflection(arg0: string, arg1: Array<string>, arg2: Array<string>, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscernmentReflection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscernmentReflection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createOrUpdateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserProfile(arg0);
            return result;
        }
    }
    async createPost(arg0: string, arg1: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1);
            return result;
        }
    }
    async createScriptureEntry(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<string>, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createScriptureEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScriptureEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getApprovedTestimonies(): Promise<Array<Testimony>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedTestimonies();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedTestimonies();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableBibleTranslations(): Promise<Array<BibleTranslation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBibleTranslations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBibleTranslations();
            return result;
        }
    }
    async getBooksForTranslation(arg0: bigint): Promise<Array<BibleBook>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooksForTranslation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooksForTranslation(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChaptersForBook(arg0: bigint): Promise<Array<BibleChapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChaptersForBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChaptersForBook(arg0);
            return result;
        }
    }
    async getDailyFeed(): Promise<[Array<ScriptureEntry>, Array<DiscernmentReflection>, Array<Testimony>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyFeed();
                return [
                    result[0],
                    result[1],
                    from_candid_vec_n3(this._uploadFile, this._downloadFile, result[2])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyFeed();
            return [
                result[0],
                result[1],
                from_candid_vec_n3(this._uploadFile, this._downloadFile, result[2])
            ];
        }
    }
    async getDiscernmentReflections(): Promise<Array<DiscernmentReflection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscernmentReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscernmentReflections();
            return result;
        }
    }
    async getFeed(arg0: bigint, arg1: bigint): Promise<Array<FeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed(arg0, arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed(arg0, arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowersCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowersCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowersCount(arg0);
            return result;
        }
    }
    async getFollowingCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingCount(arg0);
            return result;
        }
    }
    async getLastBibleLocation(): Promise<LastBibleLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastBibleLocation();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastBibleLocation();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestAgentPost(): Promise<FeedItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestAgentPost();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestAgentPost();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponsesToUser(arg0: Principal): Promise<Array<AgentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsesToUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsesToUser(arg0);
            return result;
        }
    }
    async getScriptureByTranslation(arg0: string): Promise<Array<ScriptureEntry> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptureByTranslation(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptureByTranslation(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScriptureEntries(): Promise<Array<ScriptureEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptureEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptureEntries();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVersesForChapter(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<BibleVerse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVersesForChapter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVersesForChapter(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectTestimony(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTestimony(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTestimony(arg0, arg1);
            return result;
        }
    }
    async removeReaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0);
            return result;
        }
    }
    async repostItem(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.repostItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.repostItem(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchVerse(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<BibleVerse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVerse(arg0, arg1, arg2, arg3);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVerse(arg0, arg1, arg2, arg3);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async setLastBibleLocation(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLastBibleLocation(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLastBibleLocation(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async setLastBibleLocationWithScroll(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint | null, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLastBibleLocationWithScroll(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLastBibleLocationWithScroll(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitTestimony(arg0: string, arg1: Array<string>, arg2: Array<string>, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimony(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimony(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
}
function from_candid_FeedItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedItem): FeedItem {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_LastBibleLocation_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LastBibleLocation): LastBibleLocation {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_State_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _State): State {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Testimony_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimony): Testimony {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LastBibleLocation]): LastBibleLocation | null {
    return value.length === 0 ? null : from_candid_LastBibleLocation_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeedItem]): FeedItem | null {
    return value.length === 0 ? null : from_candid_FeedItem_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ScriptureEntry>]): Array<ScriptureEntry> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BibleVerse]): BibleVerse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    references: Array<string>;
    content: string;
    authorId: Principal;
    originalItemId: [] | [bigint];
    repostCount: bigint;
    timestamp: bigint;
    itemType: {
        userPost: null;
    } | {
        scriptureEntry: null;
    } | {
        aiAgentPost: null;
    } | {
        reflection: null;
    } | {
        testimony: null;
    };
}): {
    id: bigint;
    references: Array<string>;
    content: string;
    authorId: Principal;
    originalItemId?: bigint;
    repostCount: bigint;
    timestamp: bigint;
    itemType: Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony;
} {
    return {
        id: value.id,
        references: value.references,
        content: value.content,
        authorId: value.authorId,
        originalItemId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.originalItemId)),
        repostCount: value.repostCount,
        timestamp: value.timestamp,
        itemType: from_candid_variant_n16(_uploadFile, _downloadFile, value.itemType)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    translationId: bigint;
    bookId: bigint;
    chapterId: bigint;
    verseId: [] | [bigint];
    scrollAnchor: [] | [bigint];
}): {
    translationId: bigint;
    bookId: bigint;
    chapterId: bigint;
    verseId?: bigint;
    scrollAnchor?: bigint;
} {
    return {
        translationId: value.translationId,
        bookId: value.bookId,
        chapterId: value.chapterId,
        verseId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.verseId)),
        scrollAnchor: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.scrollAnchor))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moderatorNote: [] | [string];
    content: string;
    disclaimers: Array<string>;
    authorId: Principal;
    labels: Array<string>;
    state: _State;
    scriptureReferences: Array<string>;
}): {
    moderatorNote?: string;
    content: string;
    disclaimers: Array<string>;
    authorId: Principal;
    labels: Array<string>;
    state: State;
    scriptureReferences: Array<string>;
} {
    return {
        moderatorNote: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.moderatorNote)),
        content: value.content,
        disclaimers: value.disclaimers,
        authorId: value.authorId,
        labels: value.labels,
        state: from_candid_State_n7(_uploadFile, _downloadFile, value.state),
        scriptureReferences: value.scriptureReferences
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPost: null;
} | {
    scriptureEntry: null;
} | {
    aiAgentPost: null;
} | {
    reflection: null;
} | {
    testimony: null;
}): Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony {
    return "userPost" in value ? Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony.userPost : "scriptureEntry" in value ? Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony.scriptureEntry : "aiAgentPost" in value ? Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony.aiAgentPost : "reflection" in value ? Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony.reflection : "testimony" in value ? Variant_userPost_scriptureEntry_aiAgentPost_reflection_testimony.testimony : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingModeration: null;
} | {
    approved: null;
} | {
    rejected: string;
}): {
    __kind__: "pendingModeration";
    pendingModeration: null;
} | {
    __kind__: "approved";
    approved: null;
} | {
    __kind__: "rejected";
    rejected: string;
} {
    return "pendingModeration" in value ? {
        __kind__: "pendingModeration",
        pendingModeration: value.pendingModeration
    } : "approved" in value ? {
        __kind__: "approved",
        approved: value.approved
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedItem>): Array<FeedItem> {
    return value.map((x)=>from_candid_FeedItem_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimony>): Array<Testimony> {
    return value.map((x)=>from_candid_Testimony_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
